### ISSUE TITLE
Web editor todo

### ISSUE THREAD

**Issue by Zekiah-A** [Zekiah-A/Subliminal#1]
- [ ]  Remove all spaces when generating poem name, make this safe from crashing by deletion of the "by" part.
- [ ] Chrome compatibility, seems to be using <div> instead of br, making it messy
- [ ] New line after the initial P

**Comment by Zekiah-A** [comment]
- [ ] Implement my own poem styling format as listed in technical specs
- [ ] Compression
- [ ] Decompression
- [ ] My format -> HTML converstion
- [ ] My format colour support
- [ ] My format annotation support
