### ISSUE TITLE
Subliminal music

### ISSUE THREAD

**Issue by Zekiah-A** [Zekiah-A/Subliminal#8]
![subliminal musik](https://user-images.githubusercontent.com/73035340/191507834-be7f0fb8-7fa1-4f99-8910-9c802c0c588a.png)

**Comment by Zekiah-A** [comment]
# Todo
### Feature
 - [ ] Sync to nearby devices so that the song plays at an amplified volume. Do this by using a sync qr code, that tells the server to send all data to person one to the others (for now, only main qr code sharer will be able to control media playback).

### Client -> sv protocol, I.e

- [ ] SYNCHOST (HOST KEY)

- [ ] SYNCZOMBIE (key received from scanning q)

 - [ ]PLAY (songid)

 - [ ] TIME (if we have reached a part of the song not yet cached, request an urgent skip to this part of the song data)

- [ ] LYRICS (songid)

- [ ] SEARCH (songname/songdate/songartist/lyric)

- [ ] PURGATORY (will retrieve all song ids currently in purgatory)

- [ ] UPVOTE (songid), will UPVOTE song in purgatory)

 - [ ] DOWNVOTE (songid, will downvote song in purgatory)

 - [ ] UNSYNCZOMBIE (will unbind this client from the host)

- [ ] PLAYRANDOM (send us a random songid for shuffling)

- [ ] SONGINFO (songid, will give us all info on a song, including a b64 cover image, it's name, artist, date published)

### Sv -> client protocol

- [ ] STARTPLAY (data, indicates all packets after are parts of the song the client requested)

- [ ] ENDPLAY (song packets have stopped)

- [ ] SETINFO (SONGINFO) (sv forces client to switch to a specific song, for zombie/sync)

- [ ] SETTIME (sv forces client to jump to a time in the song)

- [ ] RETPURGATORY (all packets after will be song information)

- [ ] RETRANDOM (send client a random song)

- [ ] RETLYRICS (send client back a copy of lyrics)
